// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"


using System;
using System.Collections.Generic;

using System.Globalization;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace BaseballScraper.Models.MlbDataApi
{
    [DataContract]
    public class HitterSeasonStats
    {
        [DataMember(Name="gidp")]
        [JsonProperty("gidp")]
        public string GroundedIntoDoublePlays { get; set; }

        [DataMember(Name="sac")]
        public int? Sacrifices { get; set; }

        [DataMember(Name="np")]
        public int? Np { get; set; }


        [JsonProperty("sport_hitting_tm")]
        public SportHittingTm SportHittingTm { get; set; }
    }

    // public partial class HitterSeasonStats
    // {

    // }

    public partial class SportHittingTm
    {
        [JsonProperty("copyRight")]
        public string CopyRight { get; set; }

        [JsonProperty("queryResults")]
        public HitterSeasonQueryResults QueryResults { get; set; }
    }

    public partial class HitterSeasonQueryResults
    {
        [JsonProperty("created")]
        public DateTimeOffset Created { get; set; }

        [JsonProperty("totalSize")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TotalSize { get; set; }

        [JsonProperty("row")]
        public Dictionary<string, string> Row { get; set; }
    }



}
